### ISSUE TITLE
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by xigrug** [conda-forge/netcdf4-feedstock#81] opened 2019-03-22 10:37 UTC
Issue:
from ._netCDF4 import *
ImportError: libssl.so.1.0.0: cannot open shared object file: No such file or directory

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
# Name                    Version                   Build  Channel
_ipyw_jlab_nb_ext_conf    0.1.0            py36he11e457_0    defaults
affine                    2.2.2                      py_0    conda-forge
alabaster                 0.7.10           py36h306e16b_0    defaults
altair                    2.3.0                 py36_1001    conda-forge
altgraph                  0.15                     pypi_0    pypi
anaconda-client           1.6.9                    py36_0    defaults
anaconda-navigator        1.8.4                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
anaconda-project          0.8.2            py36h44fb852_0    defaults
asn1crypto                0.24.0                   py36_0    defaults
astroid                   1.6.1                    py36_0    defaults
astropy                   2.0.3            py36h14c3975_0    defaults
atomicwrites              1.1.5                    pypi_0    pypi
attrs                     18.2.0                     py_0    conda-forge
babel                     2.5.3                    py36_0    defaults
backports                 1.0              py36hfa02d7e_1    defaults
backports.shutil_get_terminal_size 1.0.0            py36hfea85ff_2    defaults
basemap                   1.2.0            py36h50ae964_0    conda-forge
beautifulsoup4            4.6.0            py36h49b8c8c_1    defaults
bibtexparser              1.0.1                    pypi_0    pypi
bitarray                  0.8.1            py36h14c3975_1    defaults
bkcharts                  0.2              py36h735825a_0    defaults
blas                      1.0                         mkl    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
blaze                     0.11.3           py36h4e06776_0    defaults
bleach                    2.1.2                    py36_0    defaults
blosc                     1.14.4               hfc679d8_0    conda-forge
bokeh                     0.12.13          py36h2f9c1c0_0    defaults
boost-cpp                 1.67.0               h3a22d5f_0    conda-forge
boto                      2.48.0           py36h6e4cd66_1    defaults
boto3                     1.9.100                    py_0    conda-forge
botocore                  1.12.100                   py_0    conda-forge
bottleneck                1.2.1            py36haac1ea0_0    defaults
branca                    0.3.1                      py_0    conda-forge
bzip2                     1.0.6                h9a117a8_4    defaults
ca-certificates           2018.11.29           ha4d7672_0    conda-forge
cairo                     1.14.12              he6fea26_5    conda-forge
cartopy                   0.17.0          py36hd1c7146_1000    conda-forge
cdsapi                    0.1.1                    pypi_0    pypi
certifi                   2018.4.16                pypi_0    pypi
cf_units                  2.0.1                    py36_1    conda-forge
cffi                      1.11.4           py36h9745a5d_0    defaults
cftime                    1.0.0                    py36_0    conda-forge
chardet                   3.0.4            py36h0f667ec_1    defaults
cinrad                    1.2                      pypi_0    pypi
click                     7.0                        py_0    conda-forge
click-plugins             1.0.3                    pypi_0    pypi
cligj                     0.4.0                    pypi_0    pypi
cloudpickle               0.5.2                    py36_1    defaults
clyent                    1.2.2            py36h7e57e65_1    defaults
cmocean                   2.0                        py_0    conda-forge
colorama                  0.3.9            py36h489cec4_0    defaults
conda                     4.6.6                    py36_0    conda-forge
conda-build               3.4.1                    py36_0    defaults
conda-env                 2.6.0                h36134e3_1    defaults
conda-verify              2.0.0            py36h98955d8_0    defaults
contextily                1.0rc1                     py_0    conda-forge
contextlib2               0.5.5            py36h6c84a62_0    defaults
cryptography              2.5              py36h1ba5d50_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
curl                      7.63.0            hbc83047_1000    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
cycler                    0.10.0                     py_1    conda-forge
cython                    0.27.3           py36h1860423_0    defaults
cytoolz                   0.9.0            py36h14c3975_0    defaults
dash                      0.32.2                   pypi_0    pypi
dash-renderer             0.16.1                   pypi_0    pypi
dask                      0.16.1                   py36_0    defaults
dask-core                 0.16.1                   py36_0    defaults
datashape                 0.5.4            py36h3ad6b5c_0    defaults
dbus                      1.13.0               h3a4f0e9_0    conda-forge
decorator                 4.2.1                    py36_0    defaults
descartes                 1.1.0                      py_2    conda-forge
distributed               1.20.2                   py36_0    defaults
docopt                    0.6.2                      py_1    conda-forge
docutils                  0.14                  py36_1001    conda-forge
dukpy                     0.2.0                    pypi_0    pypi
eccodes                   2.8.2                ha8b302a_0    conda-forge
ecmwf-api-client          1.5.0                    pypi_0    pypi
entrypoints               0.2.3            py36h1aec115_2    defaults
et_xmlfile                1.0.1            py36hd6bccc3_0    defaults
expat                     2.2.5                he0dffb1_0    defaults
fastcache                 1.0.2            py36h14c3975_2    defaults
filelock                  2.0.13           py36h646ffb5_0    defaults
fiona                     1.7.11.post2             pypi_0    pypi
flask                     0.12.2           py36hb24657c_0    defaults
flask-compress            1.4.0                    pypi_0    pypi
flask-cors                3.0.3            py36h2d857d3_0    defaults
folium                    0.7.0                      py_0    conda-forge
fontconfig                2.13.1            h2176d3f_1000    conda-forge
freetype                  2.9.1             h94bbf69_1005    conda-forge
freexl                    1.0.5                hf837533_1    conda-forge
future                    0.16.0                   pypi_0    pypi
gdal                      2.2.4            py36hb00a9d7_1    conda-forge
geocoder                  1.38.1                   pypi_0    pypi
geographiclib             1.49                       py_0    conda-forge
geopandas                 0.3.0                    pypi_0    pypi
geoplot                   0.2.3                      py_1    conda-forge
geopy                     1.18.1                     py_0    conda-forge
geos                      3.6.2                         1    conda-forge
geotiff                   1.4.2                hb54a4aa_2    conda-forge
get_terminal_size         1.0.0                haa9412d_0    defaults
gettext                   0.19.8.1                      0    conda-forge
gevent                    1.2.2            py36h2fe25dc_0    defaults
giflib                    5.1.4                h470a237_1    conda-forge
glib                      2.55.0               h464dc38_2    conda-forge
glob2                     0.6              py36he249c77_0    defaults
gmp                       6.1.2                h6c8ec71_1    defaults
gmpy2                     2.0.8            py36hc8893dd_2    defaults
graphite2                 1.3.10               hf63cedd_1    defaults
greenlet                  0.4.12           py36h2d503a6_0    defaults
gst-plugins-base          1.12.4               h33fb286_0    defaults
gstreamer                 1.12.5               h61a6719_0    conda-forge
h5netcdf                  0.5.1                      py_0    conda-forge
h5py                      2.8.0           py36h3010b51_1003    conda-forge
harfbuzz                  1.9.0                h08d66d9_0    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.2               hc401514_3    conda-forge
heapdict                  1.0.0                    py36_2    defaults
html5lib                  1.0.1            py36h2f9c1c0_0    defaults
icu                       58.2                 h9c2bf20_1    defaults
idna                      2.6              py36h82fb2a8_1    defaults
imageio                   2.2.0            py36he555465_0    defaults
imagesize                 0.7.1            py36h52d8127_0    defaults
inflection                0.3.1                    py36_0    anaconda
intel-openmp              2018.0.0             hc7b2577_8    defaults
ipykernel                 4.8.0                    py36_0    defaults
ipython                   6.2.1            py36h88c514a_1    defaults
ipython_genutils          0.2.0            py36hb52b0d5_0    defaults
ipywidgets                7.1.1                    py36_0    defaults
iris                      2.0.0                    py36_0    conda-forge
isort                     4.2.15           py36had401c0_0    defaults
itchat                    1.2.32                   pypi_0    pypi
itsdangerous              0.24             py36h93cc618_1    defaults
jasper                    1.900.1              hff1ad4c_5    conda-forge
javascripthon             0.10                     pypi_0    pypi
jbig                      2.1                  hdba287a_0    defaults
jdcal                     1.3              py36h4c697fb_0    defaults
jedi                      0.11.1                   py36_0    defaults
jieba                     0.39                     pypi_0    pypi
jinja2                    2.10             py36ha16c418_0    defaults
jmespath                  0.9.3                      py_1    conda-forge
jpeg                      9c                   h470a237_1    conda-forge
json-c                    0.12.1               h470a237_1    conda-forge
jsonschema                2.6.0            py36h006f8b5_0    defaults
jupyter                   1.0.0                    py36_4    defaults
jupyter-echarts-pypkg     0.1.1                    pypi_0    pypi
jupyter_client            5.2.2                    py36_0    defaults
jupyter_console           5.2.0            py36he59e554_1    defaults
jupyter_core              4.4.0            py36h7c827e3_0    defaults
jupyterlab                0.31.5                   py36_0    defaults
jupyterlab_launcher       0.10.2                   py36_0    defaults
kealib                    1.4.9                h0bee7d0_2    conda-forge
kiwisolver                1.0.1           py36h6bb024c_1002    conda-forge
krb5                      1.16.1               h173b8e3_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
latexcodec                1.0.5                    pypi_0    pypi
lazy-object-proxy         1.3.1            py36h10fcdad_0    defaults
libcurl                   7.63.0            h20c2e04_1000    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libdap4                   3.19.1                        0    conda-forge
libedit                   3.1.20170329         haf1bffa_1    conda-forge
libffi                    3.2.1                hd88cf55_4    defaults
libgcc                    7.2.0                h69d50b8_2    defaults
libgcc-ng                 7.3.0                hdf63c60_0    conda-forge
libgdal                   2.2.4                he036fc0_8    conda-forge
libgfortran               3.0.0                         1    defaults
libgfortran-ng            7.2.0                h9f7466a_2    defaults
libiconv                  1.15                 h470a237_3    conda-forge
libkml                    1.3.0                hccc92b1_8    conda-forge
libnetcdf                 4.6.1              h628ed10_200    conda-forge
libopenblas               0.2.20               h9ac9557_7    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libpng                    1.6.36            h84994c4_1000    conda-forge
libpq                     11.1                 h20c2e04_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libprotobuf               3.5.2                         0    conda-forge
libpysal                  4.0.1                      py_0    conda-forge
libsodium                 1.0.15               hf101ebd_0    defaults
libspatialindex           1.8.5                hfc679d8_3    conda-forge
libspatialite             4.3.0a              h72746d6_18    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
libssh2                   1.8.0                         1    conda-forge
libstdcxx-ng              7.3.0                hdf63c60_0    conda-forge
libtiff                   4.0.9                h28f6b97_0    defaults
libtool                   2.4.6                h544aabb_3    defaults
libuuid                   2.32.1               h470a237_2    conda-forge
libxcb                    1.12                 hcd93eb1_4    defaults
libxml2                   2.9.8                h422b904_5    conda-forge
libxslt                   1.1.32               h1312cb7_0    defaults
llvmlite                  0.21.0           py36ha241eea_0    defaults
lml                       0.0.2                    pypi_0    pypi
locket                    0.2.0            py36h787c0ad_1    defaults
lxml                      4.3.1            py36h23eabaa_0    conda-forge
lzo                       2.10                 h49e0be7_2    defaults
macholib                  1.9                      pypi_0    pypi
macropy3                  1.1.0b2                  pypi_0    pypi
mapclassify               2.0.1                      py_0    conda-forge
markupsafe                1.0              py36hd9260cd_1    defaults
matplotlib                3.0.2                 py36_1002    conda-forge
matplotlib-base           3.0.2           py36h167e16e_1002    conda-forge
mccabe                    0.6.1            py36h5ad9710_1    defaults
mechanicalsoup            0.11.0                     py_0    conda-forge
mercantile                1.0.4                      py_0    conda-forge
metpy                     0.9.2                    py36_0    conda-forge
mistune                   0.8.3                    py36_0    defaults
mizani                    0.4.6                      py_0    conda-forge
mkl                       2018.0.3                      1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
mkl-service               1.1.2            py36h17a0993_4    defaults
mkl_fft                   1.0.10                   py36_0    conda-forge
mkl_random                1.0.2                    py36_0    conda-forge
more-itertools            4.2.0                    pypi_0    pypi
mpc                       1.0.3                hec55b23_5    defaults
mpfr                      3.1.5                h11a74b3_2    defaults
mpmath                    1.0.0            py36hfeacd6b_2    defaults
msgpack-python            0.5.1            py36h6bb024c_0    defaults
multipledispatch          0.4.9            py36h41da3fb_0    defaults
munch                     2.3.2                    pypi_0    pypi
myqr                      2.3.1                    pypi_0    pypi
navigator-updater         0.2.0                    py36_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
nb_conda_kernels          2.1.1                    py36_1    conda-forge
nbconvert                 5.3.1            py36hb41ffb7_0    defaults
nbformat                  4.4.0            py36h31c9010_0    defaults
ncurses                   6.1                  hfc679d8_1    conda-forge
netcdf4                   1.4.1           py36ha292673_200    conda-forge
networkx                  2.1                      py36_0    defaults
nltk                      3.2.5            py36h7532b22_0    defaults
nose                      1.3.7            py36hcdf7029_2    defaults
notebook                  5.4.0                    py36_0    defaults
numba                     0.36.2          np114py36hc6662d5_0    defaults
numexpr                   2.6.6                    py36_0    conda-forge
numpy                     1.15.4           py36h1d66e8a_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpy-base                1.15.4           py36h81de0dd_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
numpydoc                  0.7.0            py36h18f165f_0    defaults
odo                       0.5.1            py36h90ed295_0    defaults
olefile                   0.46                       py_0    conda-forge
openblas                  0.2.20                        8    conda-forge
openjpeg                  2.3.0                h0e734dc_3    conda-forge
openpyxl                  2.4.10                   py36_0    defaults
openssl                   1.1.1b               h14c3975_0    conda-forge
orbit-predictor           1.8.6                    pypi_0    pypi
owslib                    0.17.1                     py_0    conda-forge
packaging                 16.8             py36ha668100_1    defaults
palettable                3.1.1                      py_0    conda-forge
pandas                    0.24.1           py36hf484d3e_0    conda-forge
pandoc                    1.19.2.1             hea2e7c5_1    defaults
pandocfilters             1.4.2            py36ha6701b7_1    defaults
pango                     1.40.14           hf0c64fd_1003    conda-forge
parso                     0.1.1            py36h35f843b_0    defaults
partd                     0.3.8            py36h36fd896_0    defaults
patchelf                  0.9                  hf79760b_2    defaults
path.py                   10.5             py36h55ceabb_0    defaults
pathlib2                  2.3.0            py36h49efa8e_0    defaults
patsy                     0.5.1                      py_0    conda-forge
pcre                      8.41                 hc27e229_1    defaults
pefile                    2017.11.5                pypi_0    pypi
pep8                      1.7.1                    py36_0    defaults
pexpect                   4.3.1                    py36_0    defaults
pickleshare               0.7.4            py36h63277f8_0    defaults
pillow                    5.4.1           py36h00a061d_1000    conda-forge
pint                      0.8.1                    py36_0    conda-forge
pip                       18.1                     pypi_0    pypi
pixman                    0.34.0               hceecf20_3    defaults
pkginfo                   1.4.1            py36h215d178_1    defaults
plotly                    3.4.2                    pypi_0    pypi
plotnine                  0.4.0                      py_0    conda-forge
pluggy                    0.6.0            py36hb689045_0    defaults
ply                       3.10             py36hed35086_0    defaults
pooch                     0.1.1                 py36_1000    conda-forge
poppler                   0.67.0               h4d7e492_3    conda-forge
poppler-data              0.4.9                         0    conda-forge
postgresql                11.1                 h20c2e04_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
proj4                     4.9.3                         5    conda-forge
prompt_toolkit            1.0.15           py36h17d85b1_0    defaults
protobuf                  3.5.2                    py36_0    conda-forge
psutil                    5.4.3            py36h14c3975_0    defaults
psycopg2                  2.7.6.1          py36h1ba5d50_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
ptyprocess                0.5.2            py36h69acd42_0    defaults
py                        1.5.2            py36h29bf505_0    defaults
pybtex                    0.22.0                   pypi_0    pypi
pycodestyle               2.3.1            py36hf609f19_0    defaults
pycosat                   0.6.3            py36h0a5515d_0    defaults
pycparser                 2.18             py36hf9f622e_1    defaults
pycrypto                  2.6.1            py36h14c3975_7    defaults
pycurl                    7.43.0.2         py36h1ba5d50_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pydap                     3.2.2                 py36_1000    conda-forge
pyecharts                 0.5.5                    pypi_0    pypi
pyecharts-javascripthon   0.0.6                    pypi_0    pypi
pyecharts-jupyter-installer 0.0.3                    pypi_0    pypi
pyecharts-snapshot        0.1.6                    pypi_0    pypi
pyepsg                    0.4.0                      py_0    conda-forge
pyflakes                  1.6.0            py36h7bd6a15_0    defaults
pygments                  2.2.0            py36h0d3125c_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
pygrib                    2.0.3            py36h5688137_0    conda-forge
pyinstaller               3.3.1                    pypi_0    pypi
pykdtree                  1.3.1                    pypi_0    pypi
pyke                      1.1.1                    py36_0    conda-forge
pylint                    1.8.2                    py36_0    defaults
pymeteo                   0.7                      pypi_0    pypi
pyodbc                    4.0.22           py36hf484d3e_0    defaults
pyopenssl                 17.5.0           py36h20ba746_0    defaults
pyparsing                 2.3.1                      py_0    conda-forge
pypng                     0.0.18                   pypi_0    pypi
pyproj                    1.9.5.1         py36h2944ce7_1006    conda-forge
pyqrcode                  1.2.1                    pypi_0    pypi
pyqt                      4.11.4                   py36_3    conda-forge
pyresample                1.10.3                   pypi_0    pypi
pysal                     1.14.4.post2             py36_0    conda-forge
pyshp                     2.1.0                      py_0    conda-forge
pysocks                   1.6.7            py36hd97a5b1_1    defaults
pysplit                   0.3.4                    pypi_0    pypi
pytables                  3.4.4            py36h4f72b40_1    conda-forge
pytest                    3.6.0                    pypi_0    pypi
python                    3.6.7                h0371630_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
python-dateutil           2.8.0                      py_0    conda-forge
python-pptx               0.6.8                      py_0    conda-forge
pytz                      2018.9                     py_0    conda-forge
pywavelets                0.5.2            py36he602eb0_0    defaults
pyyaml                    3.12             py36hafb9ca4_1    defaults
pyzmq                     16.0.3           py36he2533c7_0    defaults
qrcode                    6.0                        py_0    conda-forge
qt                        4.8.7                         2    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
qtawesome                 0.4.4            py36h609ed8c_0    defaults
qtconsole                 4.3.1            py36h8f73b5b_0    defaults
qtpy                      1.3.1            py36h3691cc8_0    defaults
quandl                    3.3.0                    py36_0    anaconda
rasterio                  1.0.8            py36h1b5fcde_0    conda-forge
ratelim                   0.1.6                    pypi_0    pypi
readline                  7.0                  ha6073c6_4    defaults
regionmask                0.4.0                    pypi_0    pypi
requests                  2.13.0                   py36_0    conda-forge
retrying                  1.3.3                    pypi_0    pypi
rope                      0.10.7           py36h147e2ec_0    defaults
rtree                     0.8.3                    py36_0    conda-forge
ruamel_yaml               0.15.35          py36h14c3975_1    defaults
s3transfer                0.2.0                    py36_0    conda-forge
scikit-image              0.13.1           py36h14c3975_1    defaults
scikit-learn              0.19.1           py36hedc7406_0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
scipy                     1.1.0            py36hfa4b5c9_1    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main
seaborn                   0.9.0                      py_0    conda-forge
send2trash                1.4.2                    py36_0    defaults
setuptools                40.8.0                   py36_0    conda-forge
sgp4                      1.4                      pypi_0    pypi
shapely                   1.6.4           py36h0c48222_1000    conda-forge
sharppy                   1.3.0                    pypi_0    pypi
simplegeneric             0.8.1                    py36_2    defaults
singledispatch            3.4.0.3          py36h7a266c3_0    defaults
sip                       4.18                     py36_1    conda-forge
siphon                    0.8.0                 py36_1001    conda-forge
six                       1.12.0                py36_1000    conda-forge
skewt                     1.2.0                    pypi_0    pypi
snowballstemmer           1.2.1            py36h6febd40_0    defaults
snuggs                    1.4.1                      py_1    conda-forge
sortedcollections         0.5.3            py36h3c761f9_0    defaults
sortedcontainers          1.5.9                    py36_0    defaults
sphinx                    1.6.6                    py36_0    defaults
sphinxcontrib             1.0              py36h6d0f590_1    defaults
sphinxcontrib-websupport  1.0.1            py36hb5cb234_1    defaults
spyder                    3.2.6                    py36_0    defaults
sqlalchemy                1.2.1            py36h14c3975_0    defaults
sqlite                    3.25.3               hb1c47c0_0    conda-forge
statsmodels               0.9.0            py36h7eb728f_0    conda-forge
sympy                     1.1.1            py36hc6d1c1c_0    defaults
tblib                     1.3.2            py36h34cf8b6_0    defaults
terminado                 0.8.1                    py36_1    defaults
testpath                  0.3.1            py36h8cadb63_0    defaults
tk                        8.6.9             h84994c4_1000    conda-forge
toolz                     0.9.0                    py36_0    defaults
tornado                   4.5.3           py36h14c3975_1001    conda-forge
traitlets                 4.3.2            py36h674d592_0    defaults
typing                    3.6.2            py36h7da032a_0    defaults
udunits2                  2.2.26                        1    conda-forge
unicodecsv                0.14.1           py36ha668878_0    defaults
unixodbc                  2.3.4                hc36303a_1    defaults
urllib3                   1.20                     py36_1    conda-forge
util-linux                2.21                          0    https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free
vincent                   0.4.4                      py_1    conda-forge
wcwidth                   0.1.7            py36hdf4376a_0    defaults
webencodings              0.5.1            py36h800622e_1    defaults
webob                     1.8.5                      py_0    conda-forge
werkzeug                  0.14.1                   py36_0    defaults
wheel                     0.33.1                   py36_0    conda-forge
widgetsnbextension        3.1.0                    py36_0    defaults
wordcloud                 1.4.1                    py36_0    conda-forge
wrapt                     1.10.11          py36h28b7045_0    defaults
wrf-python                1.3.0            py36h18b3941_0    conda-forge
wxpy                      0.3.9.8                  pypi_0    pypi
xarray                    0.10.7                   py36_0    conda-forge
xerces-c                  3.2.0                         0    conda-forge
xlrd                      1.1.0            py36h1db9f0c_1    defaults
xlsxwriter                1.0.2            py36h3de1aca_0    defaults
xlwt                      1.3.0            py36h7b00a1f_0    defaults
xorg-kbproto              1.0.7                h470a237_2    conda-forge
xorg-libice               1.0.9                h470a237_4    conda-forge
xorg-libsm                1.2.3                h8c8a85c_0    conda-forge
xorg-libx11               1.6.6                h470a237_0    conda-forge
xorg-libxext              1.3.3                h470a237_4    conda-forge
xorg-libxrender           0.9.10               h470a237_2    conda-forge
xorg-renderproto          0.11.1               h470a237_2    conda-forge
xorg-xextproto            7.3.0                h470a237_2    conda-forge
xorg-xproto               7.0.31               h470a237_7    conda-forge
xz                        5.2.4                h470a237_1    conda-forge
yaml                      0.1.7                had09818_2    defaults
zeromq                    4.2.2                hbedb6e5_2    defaults
zict                      0.1.3            py36h3a3bf81_0    defaults
zlib                      1.2.11               ha838bed_2    defaults

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):

conda 4.6.6
Linux admin 3.10.0-693.el7.x86_64 #1 SMP Tue Aug 22 21:09:27 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

```
$ conda info

```
 active environment : None
            shell level : 0
       user config file : /public/home/hysplit/.condarc
 populated config files : /public/home/hysplit/.condarc
          conda version : 4.6.6
    conda-build version : 3.4.1
         python version : 3.6.7.final.0
       base environment : /public/home/hysplit/software/anaconda3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/main/noarch
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/linux-64
                          https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
          package cache : /public/home/hysplit/software/anaconda3/pkgs
                          /public/home/hysplit/.conda/pkgs
       envs directories : /public/home/hysplit/software/anaconda3/envs
                          /public/home/hysplit/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.6 requests/2.13.0 CPython/3.6.7 Linux/3.10.0-693.el7.x86_64 centos/7.4.1708 glibc/2.17
                UID:GID : 1006:100
             netrc file : /public/home/hysplit/.netrc
           offline mode : False

**Comment by xylar** [comment] 2019-03-22 15:09
`libgcc-ng 7.3.0` from `conda-forge` is currently marked as broken.  The only way to install `netcdf4=1.4.1` currently is to include the current `libgcc-ng` from the `defaults` channel.  Could you try creating a new environment as follows and see if you are able to import `netcdf4` successfully there?

```
$ conda create -n test_netcdf4 -c conda-forge -c defaults python=3.6 netcdf4=1.4.1
...
The following NEW packages will be INSTALLED:
...
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-8.2.0-hdf63c60_1
...
  netcdf4            conda-forge/linux-64::netcdf4-1.4.1-py36ha292673_200
...
$ conda activate test_netcdf4
$ python -c "import netCDF4"
```
That worked successfully for me.  If that works for you, I'm afraid your best option might be to build a new environment with a different `libgcc`.  It looks like you've got a lot of packages installed in your current one so that might take some time but I doubt you will have much success if you just try to reinstall packages in your current environment even if you replace the broken `libgcc-ng` and other packages.

@ocefpaf, would your advice be any different?

**Comment by ocefpaf** [comment] 2019-03-22 15:34
The problem is not `libgcc` but the fact that the package is too old and the `openssl` migrated to a new version. We won't rebuild `netcdf4 1.4.1` with latest `openssl` I recommend you to upgrade your version.

**Closed as completed by ocefpaf** 2019-03-22 15:34 UTC

**Comment by ivanomarot** [comment] 2019-04-22 07:55
Hello! I am also having this problem in netcdf4 version 1.5.0.1.

`from ._netCDF4 import *
ImportError: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory`

What is the version for the new openssl?

[root@mtl-hdops01d ~]# ls -lrth /hadoop/opt/anaconda3-5.0.1/lib/|grep -i cryp
-rwxrwxr-x  2 otdsi-dev-bot hadoop  135K Feb 26 13:17 libk5crypto.so.3.1
lrwxrwxrwx  1 otdsi-dev-bot hadoop    18 Apr 22 05:45 libk5crypto.so.3 -> libk5crypto.so.3.1
lrwxrwxrwx  1 otdsi-dev-bot hadoop    18 Apr 22 05:45 libk5crypto.so -> libk5crypto.so.3.1
-rwxrwxr-x  1 otdsi-dev-bot hadoop  6.4M Apr 22 07:40 libcrypto.a
-rwxrwxr-x  1 otdsi-dev-bot hadoop  3.3M Apr 22 07:40 libcrypto.so.1.1
lrwxrwxrwx  1 otdsi-dev-bot hadoop    16 Apr 22 07:40 libcrypto.so -> libcrypto.so.1.1

**Comment by ocefpaf** [comment] 2019-04-22 13:05
> Hello! I am also having this problem in netcdf4 version 1.5.0.1.

Please open a new issue with provide all the information requested in the issue boilerplate. We cannot help without that information. BTW, a fresh installation works for me on Linux:

```
conda create --name TEST python=3.7 netcdf4
conda activate TEST
python -c "import netCDF4; print(netCDF4.__version__)"    
1.5.0.1
```


Also see https://conda-forge.org/docs/user/tipsandtricks.html#how-to-fix-it
