### ISSUE TITLE
conda-forge netCDF nc-config --libs produces incorrect results

### ISSUE THREAD

**Issue by czender** [conda-forge/netcdf4-feedstock#59] opened 2018-09-17 00:54 UTC
Issue:
The Conda-forge netCDF nc-config behaves strangely.
The response to the --libs argument prepends and extra path:

```
zender@aerosol:~$ /Users/zender/anaconda/bin/nc-config --libs
-L/Users/zender/anaconda//Users/zender/anaconda/lib -lnetcdf -lmfhdf -ldf -lhdf5_hl -lhdf5 -lc++ -lpthread -lz -ldl -lm -lcurl
zender@aerosol:~$ /Users/zender/anaconda/bin/nc-config --cflags
-I/Users/zender/anaconda/include

```
The error is the partially duplicated path immediately following `-L`. The same occurs with Conda-forge nc-config on my Fedora machine, but when I build netCDF from scratch, nc-config behaves correctly:

```
zender@skyglow:~$ /usr/local/bin/nc-config --libs
-L/usr/local/lib -lnetcdf

```
Hence this seems like an issue with the conda-forge netcdf feedstock.
Can anyone else reproduce this behavior?

Charlie

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
zender@aerosol:~$ conda list
# packages in environment at /Users/zender/anaconda:
#
# Name                    Version                   Build  Channel
appdirs                   1.4.3                      py_1    conda-forge
appnope                   0.1.0                    py27_0    conda-forge
asn1crypto                0.24.0                     py_1    conda-forge
astropy                   2.0.8                    py27_0    conda-forge
atomicwrites              1.1.5                    py27_0    conda-forge
attrs                     18.1.0                     py_1    conda-forge
automat                   0.7.0                      py_1    conda-forge
backports                 1.0                      py27_1    conda-forge
backports.functools_lru_cache 1.5                        py_1    conda-forge
backports.shutil_get_terminal_size 1.0.0                      py_3    conda-forge
backports_abc             0.5                      py27_0    conda-forge
blas                      1.0                         mkl  
bleach                    2.1.4                      py_1    conda-forge
bokeh                     0.13.0                   py27_0    conda-forge
bottleneck                1.2.1            py27h7eb728f_1    conda-forge
ca-certificates           2018.8.24            ha4d7672_0    conda-forge
cartopy                   0.16.0           py27h81b52dc_1    conda-forge
cdo                       1.9.4                h1d09544_1    conda-forge
certifi                   2018.8.24                py27_1    conda-forge
cffi                      1.11.5           py27h5e8e0c9_1    conda-forge
cftime                    1.0.0            py27h7eb728f_1    conda-forge
chardet                   3.0.4                    py27_3    conda-forge
clangdev                  6.0.1                 default_1    conda-forge
click                     6.7                        py_1    conda-forge
cloudpickle               0.5.3                      py_0    conda-forge
conda                     4.5.11                   py27_0    conda-forge
conda-env                 2.6.0                         1    conda-forge
configparser              3.5.0                    py27_0    conda-forge
constantly                15.1.0                     py_0    conda-forge
cryptography              2.3              py27hdffb7b8_0    conda-forge
cryptography-vectors      2.3                      py27_1    conda-forge
curl                      7.61.0               h93b3f91_1    conda-forge
cycler                    0.10.0                     py_1    conda-forge
cyordereddict             1.0.0            py27h470a237_2    conda-forge
cython                    0.28.5           py27hfc679d8_0    conda-forge
cytoolz                   0.9.0.1          py27h470a237_0    conda-forge
dask                      0.18.2                     py_0    conda-forge
dask-core                 0.18.2                     py_0    conda-forge
decorator                 4.3.0                      py_0    conda-forge
distributed               1.22.1                   py27_0    conda-forge
eccodes                   2.8.0                         0    conda-forge
ecmwf_grib                1.27.0                        0    conda-forge
entrypoints               0.2.3                    py27_2    conda-forge
enum34                    1.1.6                    py27_1    conda-forge
esmf                      7.1.0r                        1    conda-forge
expat                     2.2.5                hfc679d8_1    conda-forge
fftw                      3.3.8                h470a237_0    conda-forge
freetype                  2.8.1                hfa320df_1    conda-forge
funcsigs                  1.0.2                      py_2    conda-forge
functools32               3.2.3.2                  py27_2    conda-forge
futures                   3.2.0                    py27_0    conda-forge
geos                      3.6.2                hfc679d8_2    conda-forge
gsl                       2.2.1                h002c638_3  
h5json                    1.1.0                     <pip>
h5netcdf                  0.6.1                      py_0    conda-forge
h5py                      2.7.1                     <pip>
h5py                      2.8.0            py27h470a237_0    conda-forge
hdf4                      4.2.13                        0    conda-forge
hdf5                      1.10.1                        2    conda-forge
heapdict                  1.0.0                    py27_0    conda-forge
html5lib                  1.0.1                      py_0    conda-forge
hyperlink                 17.3.1                     py_0    conda-forge
icu                       58.2                 hfc679d8_0    conda-forge
idna                      2.7                      py27_2    conda-forge
incremental               17.5.0                     py_0    conda-forge
intel-openmp              2018.0.3                      0  
ipaddress                 1.0.22                     py_1    conda-forge
ipykernel                 4.8.2                    py27_0    conda-forge
ipython                   5.8.0                    py27_0    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
ipywidgets                7.4.0                      py_0    conda-forge
jasper                    1.900.1                       4    conda-forge
jaws                      0.4.8                    py27_0    conda-forge
jinja2                    2.10                       py_1    conda-forge
joblib                    0.12.2                     py_0    conda-forge
jpeg                      9c                   h470a237_0    conda-forge
jsonschema                2.6.0                    py27_1    conda-forge
jupyter                   1.0.0                      py_1    conda-forge
jupyter_client            5.2.3                      py_1    conda-forge
jupyter_console           5.2.0                    py27_0    conda-forge
jupyter_core              4.4.0                      py_0    conda-forge
kiwisolver                1.0.1                    py27_1    conda-forge
krb5                      1.14.6                        0    conda-forge
libcxx                    6.0.1                         0    conda-forge
libffi                    3.2.1                         3    conda-forge
libgcc                    4.8.5                         1  
libgfortran               3.0.1                h93005f0_2  
libiconv                  1.15                 h470a237_1    conda-forge
libnetcdf                 4.6.1                         2    conda-forge
libpng                    1.6.34               ha92aebf_1    conda-forge
libsodium                 1.0.16                        0    conda-forge
libssh2                   1.8.0                h5b517e9_2    conda-forge
libtiff                   4.0.9                he6b73bb_1    conda-forge
libxml2                   2.9.8                h422b904_2    conda-forge
libxslt                   1.1.32               h88dbc4e_1    conda-forge
linecache2                1.0.0                    py27_0    conda-forge
llvm-meta                 6.0.1                         0    conda-forge
llvmdev                   6.0.1                hf8ce74a_2    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.2.4            py27hc9114bc_0    conda-forge
markupsafe                1.0                      py27_0    conda-forge
matplotlib                2.2.2                    py27_1    conda-forge
mistune                   0.8.3            py27h470a237_2    conda-forge
mkl                       2018.0.3                      1  
mkl_fft                   1.0.6                    py27_0    conda-forge
mkl_random                1.0.1                    py27_0    conda-forge
more-itertools            4.2.0                    py27_1    conda-forge
mpi                       1.0                       mpich    conda-forge
mpich                     3.2.1                h26a2512_4    conda-forge
msgpack-python            0.5.6            py27h2d50403_2    conda-forge
nbconvert                 5.3.1                      py_1    conda-forge
nbformat                  4.4.0                      py_1    conda-forge
nco                       4.7.5                         1    conda-forge
ncurses                   6.1                  hfc679d8_1    conda-forge
netcdf-fortran            4.4.4                         7    conda-forge
netcdf4                   1.4.0                    py27_0    conda-forge
notebook                  5.6.0                    py27_0    conda-forge
numpy                     1.15.1           py27h648b28d_0  
numpy-base                1.15.1           py27h8a80b8c_0  
olefile                   0.45.1                     py_1    conda-forge
openblas                  0.2.20                        8    conda-forge
openssl                   1.0.2o               h470a237_1    conda-forge
owslib                    0.16.0                     py_0    conda-forge
packaging                 17.1                       py_0    conda-forge
pandas                    0.23.4           py27hf8a1672_0    conda-forge
pandoc                    2.2.2                hde52d81_1    conda-forge
pandocfilters             1.4.2                      py_1    conda-forge
partd                     0.3.8                      py_1    conda-forge
pathlib2                  2.3.2                    py27_0    conda-forge
pexpect                   4.6.0                    py27_0    conda-forge
pickleshare               0.7.4                    py27_0    conda-forge
pillow                    5.2.0            py27h2dc6135_1    conda-forge
pip                       18.0                     py27_1    conda-forge
pluggy                    0.7.1                      py_0    conda-forge
proj4                     4.9.3                         5    conda-forge
prometheus_client         0.3.0                      py_0    conda-forge
prompt_toolkit            1.0.15                     py_1    conda-forge
psutil                    5.4.6                    py27_0    conda-forge
ptyprocess                0.6.0                    py27_0    conda-forge
py                        1.5.4                      py_0    conda-forge
pyasn1                    0.4.4                      py_0    conda-forge
pyasn1-modules            0.2.1                      py_0    conda-forge
pycosat                   0.6.3            py27h470a237_1    conda-forge
pycparser                 2.18                       py_1    conda-forge
pycrypto                  2.6.1                    py27_1    conda-forge
pyepsg                    0.3.2                      py_1    conda-forge
pygments                  2.2.0                      py_1    conda-forge
pyhamcrest                1.9.0                      py_2    conda-forge
pyopenssl                 18.0.0                   py27_0    conda-forge
pyparsing                 2.2.0                      py_1    conda-forge
pyproj                    1.9.5.1                  py27_0    conda-forge
pyqt                      5.6.0            py27h8210e8a_7    conda-forge
pyshp                     1.2.12                     py_0    conda-forge
pysocks                   1.6.8                    py27_1    conda-forge
pytest                    3.7.1                    py27_0    conda-forge
python                    2.7.15               h43f7c74_0    conda-forge
python-dateutil           2.7.3                      py_0    conda-forge
pytz                      2018.5                     py_0    conda-forge
pyyaml                    3.12                     py27_1    conda-forge
pyzmq                     17.1.2           py27hae99301_0    conda-forge
qt                        5.6.2                hd4c90f3_9    conda-forge
qtconsole                 4.4.1            py27h8a2030e_0    conda-forge
readline                  7.0                  haf1bffa_1    conda-forge
requests                  2.19.1                   py27_1    conda-forge
ruamel_yaml               0.15.46          py27h470a237_0    conda-forge
scandir                   1.7              py27h470a237_1    conda-forge
scipy                     1.1.0            py27hf1f7d93_0  
send2trash                1.5.0                      py_0    conda-forge
service_identity          17.0.0                     py_0    conda-forge
setuptools                40.0.0                   py27_1    conda-forge
shapely                   1.6.4            py27h164cb2d_1    conda-forge
simplegeneric             0.8.1                      py_1    conda-forge
singledispatch            3.4.0.3                  py27_0    conda-forge
sip                       4.18.1           py27hfc679d8_0    conda-forge
six                       1.11.0                   py27_1    conda-forge
six                       1.10.0                    <pip>
sortedcontainers          2.0.4                      py_1    conda-forge
sqlite                    3.24.0               h2f33b56_0    conda-forge
ssl_match_hostname        3.5.0.1                  py27_1    conda-forge
subprocess32              3.5.2                    py27_0    conda-forge
tblib                     1.3.2                      py_1    conda-forge
terminado                 0.8.1                    py27_0    conda-forge
testpath                  0.3.1                    py27_0    conda-forge
tk                        8.6.8                         0    conda-forge
toolz                     0.9.0                      py_0    conda-forge
tornado                   5.1              py27h470a237_1    conda-forge
traceback2                1.4.0                    py27_0    conda-forge
traitlets                 4.3.2                    py27_0    conda-forge
twisted                   18.7.0           py27h470a237_1    conda-forge
udunits2                  2.2.26                        1    conda-forge
unittest2                 1.1.0                      py_0    conda-forge
urllib3                   1.23                     py27_1    conda-forge
wcwidth                   0.1.7                      py_1    conda-forge
webencodings              0.5.1                    py27_0    conda-forge
wheel                     0.31.1                   py27_1    conda-forge
widgetsnbextension        3.4.0                    py27_0    conda-forge
xarray                    0.10.8                   py27_0    conda-forge
xz                        5.2.4                h470a237_0    conda-forge
yaml                      0.1.7                h470a237_1    conda-forge
zeromq                    4.2.5                hfc679d8_5    conda-forge
zict                      0.1.3                      py_0    conda-forge
zlib                      1.2.11               h470a237_3    conda-forge
zope.interface            4.5.0            py27h470a237_0    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
(I could not find the conda-info command)
```
</details>

**Comment by xylar** [comment] 2018-10-19 13:55
@czender, I have seen this issue as well in the past.

**Comment by ocefpaf** [comment] 2018-10-19 14:03
This is a duplicate of https://github.com/conda-forge/libnetcdf-feedstock/issues/57 let's keep the discussion there.

**Closed as completed by ocefpaf** 2018-10-19 14:03 UTC
